### PR TITLE
Chore: export types

### PR DESCRIPTION
**Pull request by rolznz**

### CODE REVIEW

**Comment by bumi** [comment]
Isn't this somehow done by default: https://github.com/getAlby/alby-tools/blob/master/package.json#L10

**Comment by rolznz** [comment]
> Isn't this somehow done by default: https://github.com/getAlby/alby-tools/blob/master/package.json#L10

@bumi it does work, but the types need to be imported like this:
```
import { Event, NostrProvider } from "alby-tools/dist/types";
```

rather than just from "alby-tools".

**Comment by bumi** [comment]
How do other packages do this. As there is such an entry in the npm package.json there must be some standard solutions I guess.

**Comment by rolznz** [comment]
@bumi I could be wrong, but the types field seems to be used for projects that are not natively typescript, and have an accompanying .d.ts file where they declare their types. Most other packages I have seen export types from the index.ts file.

Because this project is written in typescript, the types can be exported from the index file along with everything else.

From https://stackoverflow.com/a/56371055/4562693

**Comment by JPLACLAU** [comment]
As a newcommer with little experience, I spend quite some time with the issue since I find it hard importing a function from .d.ts typescript file. This may be obvious for experienced developers. 

I do think It would have been easier for me if the helpers for SatToUSD conversion was easily imported with this import structure: 

`
import { LightningAddress, fiat } from 'alby-tools';
`

Also, may I recommend adding ".toFixed(2);" to the answer provided by the getFiatValue function, since there is little to no use to have more than 2 decimals on a USD amount value, and while adding items on my testshop, I had strange long decimals like for example "142,0000034 USD".

Thanks!

**Comment by bumi** [comment]
> Also, may I recommend adding .toFixed(2); to the answer provided by the getFiatValue function, since there is little to no use to have more than 2 decimals on a USD amount value, and while adding items on my testshop, I had strange long decimals like for example "142,0000034 USD".

there are currencies with more than 2 decimal points. use the `getFormattedFiatValue` for this. it uses the JS `toLocaleString` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

**Pull request merged**
